import java.util.ArrayList;
/**
 * 학생 데이터
 */
public class Student {

    int grade; // 학년 1~3
    int classroom; // 반 1~14
    ArrayList<Route> routeAL;
    Student(int grade, int classroom){
        this.grade = grade;
        this.classroom = classroom;
        this.routeAL = setupRouteAL(grade,classroom);
    }

    /**
     * 학생 이동 경로 반환
     * @param grade 학년
     * @param classroom 반
     * @return 학생 이동 경로
     */
    private ArrayList<Route> setupRouteAL(int grade,int classroom){
        return switch (grade) {
            case 1 -> setupRouteGrade1(classroom);
            case 2 -> setupRouteGrade2(classroom);
            case 3 -> setupRouteGrade3(classroom);
            default -> null;
        };
    }

    private ArrayList<Route> setupRouteGrade1(int classroom){
        ArrayList<Route> routes = new ArrayList<>();
        switch (classroom){
            case 1:
                routes.add(new Route(1,3,"000"));
                routes.add(new Route(1,3,"100"));
                routes.add(new Route(1,3,"101"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 2:
                routes.add(new Route(1,3,"001"));
                routes.add(new Route(1,3,"100"));
                routes.add(new Route(1,3,"101"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 3:
                routes.add(new Route(1,3,"002"));
                routes.add(new Route(1,3,"101"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 4:
                routes.add(new Route(1,4,"000"));
                routes.add(new Route(1,4,"100"));
                routes.add(new Route(1,4,"101"));
                routes.add(new Route(1,4,"102"));
                routes.add(new Route(1,4,"103"));
                routes.add(new Route(1,4,"200"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 5:
                routes.add(new Route(1,4,"001"));
                routes.add(new Route(1,4,"101"));
                routes.add(new Route(1,4,"102"));
                routes.add(new Route(1,4,"103"));
                routes.add(new Route(1,4,"200"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 6:
                routes.add(new Route(1,4,"002"));
                routes.add(new Route(1,4,"102"));
                routes.add(new Route(1,4,"103"));
                routes.add(new Route(1,4,"200"));
                routes.add(new Route(1,3,"200"));
                routes.add(new Route(1,2,"200"));
                routes.add(new Route(1,2,"100"));
                routes.add(new Route(1,2,"101"));
                routes.add(new Route(1,2,"102"));
                routes.add(new Route(1,2,"103"));
                routes.add(new Route(1,2,"104"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 7:
                routes.add(new Route(0,3,"005"));
                routes.add(new Route(0,3,"105"));
                routes.add(new Route(0,3,"106"));
                routes.add(new Route(0,3,"107"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 8:
                routes.add(new Route(0,3,"006"));
                routes.add(new Route(0,3,"106"));
                routes.add(new Route(0,3,"107"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 9:
                routes.add(new Route(0,3,"007"));
                routes.add(new Route(0,3,"107"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 10:
                routes.add(new Route(0,3,"008"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 11:
                routes.add(new Route(0,3,"009"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 12:
                routes.add(new Route(0,2,"000"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 13:
                routes.add(new Route(0,1,"000"));
                routes.add(new Route(0,1,"100"));
                routes.add(new Route(0,1,"101"));
                routes.add(new Route(0,1,"102"));
                routes.add(new Route(0,1,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));

        }
        return routes;
    }
    private ArrayList<Route> setupRouteGrade2(int classroom){
        ArrayList<Route> routes = new ArrayList<>();
        switch (classroom){
            case 1:
                routes.add(new Route(0,3,"000"));
                routes.add(new Route(0,3,"100"));
                routes.add(new Route(0,3,"101"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 2:
                routes.add(new Route(0,3,"001"));
                routes.add(new Route(0,3,"101"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 3:
                routes.add(new Route(0,3,"002"));
                routes.add(new Route(0,3,"102"));
                routes.add(new Route(0,3,"101"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 4:
                routes.add(new Route(0,3,"003"));
                routes.add(new Route(0,3,"103"));
                routes.add(new Route(0,3,"104"));
                routes.add(new Route(0,3,"105"));
                routes.add(new Route(0,3,"106"));
                routes.add(new Route(0,3,"107"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 5:
                routes.add(new Route(0,3,"004"));
                routes.add(new Route(0,3,"104"));
                routes.add(new Route(0,3,"105"));
                routes.add(new Route(0,3,"106"));
                routes.add(new Route(0,3,"107"));
                routes.add(new Route(0,3,"108"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 6:
                routes.add(new Route(0,4,"010"));
                routes.add(new Route(0,4,"102"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 7:
                routes.add(new Route(0,4,"011"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 8:
                routes.add(new Route(0,4,"000"));
                routes.add(new Route(0,4,"100"));
                routes.add(new Route(0,4,"101"));
                routes.add(new Route(0,4,"102"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 9:
                routes.add(new Route(0,4,"001"));
                routes.add(new Route(0,4,"101"));
                routes.add(new Route(0,4,"102"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 10:
                routes.add(new Route(0,4,"002"));
                routes.add(new Route(0,4,"102"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 11:
                routes.add(new Route(0,4,"003"));
                routes.add(new Route(0,4,"103"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 12:
                routes.add(new Route(0,4,"004"));
                routes.add(new Route(0,4,"104"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 13:
                routes.add(new Route(0,4,"005"));
                routes.add(new Route(0,4,"105"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 14:
                routes.add(new Route(0,4,"006"));
                routes.add(new Route(0,4,"106"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
        }

        return routes;
    }
    private ArrayList<Route> setupRouteGrade3(int classroom){
        ArrayList<Route> routes = new ArrayList<>();
        switch (classroom){
            case 1:
                routes.add(new Route(0,5,"000"));
                routes.add(new Route(0,5,"100"));
                routes.add(new Route(0,5,"101"));
                routes.add(new Route(0,5,"200"));
                routes.add(new Route(0,4,"200"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 2:
                routes.add(new Route(0,5,"001"));
                routes.add(new Route(0,5,"101"));
                routes.add(new Route(0,5,"200"));
                routes.add(new Route(0,4,"200"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 3:
                routes.add(new Route(0,5,"002"));
                routes.add(new Route(0,5,"102"));
                routes.add(new Route(0,5,"101"));
                routes.add(new Route(0,5,"200"));
                routes.add(new Route(0,4,"200"));
                routes.add(new Route(0,3,"200"));
                routes.add(new Route(0,2,"200"));
                routes.add(new Route(0,2,"300"));
            case 4:
                routes.add(new Route(0,5,"003"));
                routes.add(new Route(0,5,"103"));
                routes.add(new Route(0,5,"104"));
                routes.add(new Route(0,5,"105"));
                routes.add(new Route(0,5,"106"));
                routes.add(new Route(0,5,"107"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 5:
                routes.add(new Route(0,5,"004"));
                routes.add(new Route(0,5,"104"));
                routes.add(new Route(0,5,"105"));
                routes.add(new Route(0,5,"106"));
                routes.add(new Route(0,5,"107"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 6:
                routes.add(new Route(0,5,"005"));
                routes.add(new Route(0,5,"105"));
                routes.add(new Route(0,5,"106"));
                routes.add(new Route(0,5,"107"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 7:
                routes.add(new Route(0,5,"006"));
                routes.add(new Route(0,5,"106"));
                routes.add(new Route(0,5,"107"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 8:
                routes.add(new Route(0,5,"007"));
                routes.add(new Route(0,5,"107"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 9:
                routes.add(new Route(0,5,"008"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 10:
                routes.add(new Route(0,5,"009"));
                routes.add(new Route(0,5,"108"));
                routes.add(new Route(0,5,"201"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 11:
                routes.add(new Route(0,4,"009"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 12:
                routes.add(new Route(0,4,"008"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));
            case 13:
                routes.add(new Route(0,4,"007"));
                routes.add(new Route(0,4,"107"));
                routes.add(new Route(0,4,"108"));
                routes.add(new Route(0,4,"201"));
                routes.add(new Route(0,3,"201"));
                routes.add(new Route(0,2,"201"));
                routes.add(new Route(0,2,"105"));
                routes.add(new Route(0,2,"104"));
                routes.add(new Route(0,2,"103"));
                routes.add(new Route(0,2,"102"));
                routes.add(new Route(0,2,"101"));
                routes.add(new Route(0,2,"100"));
                routes.add(new Route(0,2,"300"));

        }

        return routes;
    }
}
